app:
    env: "develop"
    debug: true
    port: "3100"
loket:
    url: "http://api.sandbox.loket.com"
    key: "sandbox-TgkDRgyHuRcz5P9aksfTsBqu1GQ49Va0"
    username: "mataharimall"
    password: "mataharimall23"
mysql:
    master: "root:matahari@(mysqlserver:3306)/MMDBV3?charset=utf8&parseTime=True&loc=Local"
    slave: "root:matahari@(mysqlserver:3306)/MMDBV3?charset=utf8&parseTime=True&loc=Local"
redis:
    master: "redisserver:6379"
    slave: "redisslave:6379"
mongo:
    master: "mongodbserver"
    database: "mataharimall"
